MAX_ITER = 10000
SIZE_OF_FIRST_POPULATION = 10000
SIZE_OF_POPULATION = 1000
BITS_FOR_VERTEX = 8
REPRODUCTION_PROBABILITY = 90
REPRODUCTION_POINT_DIVIDER = 30
MUTATE_MEMBER_PROBABILITY = 30
MUTATE_GEN_PROBABILITY = 50
MUTATE_MISSMATCHED_GEN_PROBABILITY_WEIGHT = 50
NONE_PROB = 0.4
EMPTY_VERTEX = 3

SHORTEST = "shortest"
BEST = "best"

INVALID_PATH_PENALTY = 100
LOOP_IN_PATH_PENALTY = 10
INVALID_SOURCE_AND_DESTINATION_PENALTY = 500
OVERLOADED_PATH_PENALTY = 1000
DISRUPTED_FLOW_PENALTY = 1000

MAX_PATH_LENGTH = 25