SIZE_OF_FIRST_POPULATION = 10000
SIZE_OF_POPULATION = 1000
BITS_FOR_VERTEX = 8
REPRODUCTION_PROBABILITY = 30
REPRODUCTION_POINT_DIVIDER = 20
MUTATE_MEMBER_PROBABILITY = 90
MUTATE_GEN_PROBABILITY = 90
EMPTY_VERTEX = 1

SHORTEST = "shortest"
BEST = "best"

INVALID_PATH_PENALTY = 1000
INVALID_SOURCE_AND_DESTINATION_PENALTY = 500
OVERLOADED_PATH_PENALTY = 1000
DISRUPTED_FLOW_PENALTY = 1000
