SIZE_OF_POPULATION = 1000
BITS_FOR_VERTEX = 8
REPRODUCTION_PROBABILITY = 99
REPRODUCTION_POINT_DEVIDER = 10
MUTATE_MEMBER_PROBABILITY = 1
MUTATE_GEN_PROBABILITY = 1

SHORTEST = "shortest"
BEST = "best"

INVALID_PATH_PENALTY = 1000
OVERLOADED_PATH_PENALTY = 1000
DISRUPTED_FLOW_PENALTY = 1000
